name: Build and deploy Python app to Azure Web App - manish-webapp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev gcc g++

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive application
        run: |
          zip -r release.zip . -x "venv/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_C51BE59D88C1493E9CD21045A97A3E4E }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_C3C95011255F486B836ACE3706024D6A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F55D1B10E58C4D07BC3C77A83F641B60 }}

      - name: Sync HTML templates to $web
        run: |
          az storage blob upload-batch \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --account-key  "${{ secrets.STORAGE_ACCOUNT_KEY }}" \
            --destination '$web' \
            --source      templates/

      - name: Sync product images to images container
        run: |
          az storage blob upload-batch \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --account-key  "${{ secrets.STORAGE_ACCOUNT_KEY }}" \
            --destination images \
            --source      static/images/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name:  'manish-webapp'
          slot-name: 'production'
          package:   'release.zip'
